export const LOAD_WALLETS_SUCCESS = 'LOAD_WALLETS_SUCCESS';
export const LOAD_WALLET_SUCCESS = 'LOAD_WALLET_SUCCESS';
export const GAS_TRANFER_SUCCESS = 'GAS_TRANFER_SUCCESS';
export const GAS_USING_SUCCESS = 'GAS_USING_SUCCESS';
